### ISSUE TITLE
Setup automated build release

### ISSUE THREAD

**Issue by mageddo** [mageddo/toggle-first#8]
### Current Behavior
I have to manually build the app to check if it's building and manually upload the archives to nexus repository

### Expected Behavior
Build the project when it is merged and upload the archives to nexus repository

### Tasks
* [x] Setup travis master branch build
* [x] Setup travis pull request branch build
* [x] Setup gradle release plugin
* [x] Setup nexus release
